# Generated by Django 4.2.2 on 2024-11-14 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0003_alter_mailingattempt_send_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="start_time",
            field=models.DateTimeField(verbose_name="дата начала рассылки"),
        ),
        migrations.AlterField(
            model_name="mailingattempt",
            name="send_time",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Время отправки"
            ),
        ),
    ]
